version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_new
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: empdb
      MYSQL_USER: empuser
      MYSQL_PASSWORD: emppassword
    ports:
      - "3306:3306"

  backend:
    build: ./WebApplication1
    container_name: empwebapi_backend
    ports:
      - "5000:80"
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=empdb;User=empuser;Password=emppassword;

  gateway:
    build: ./YarpGateway
    container_name: empwebapi_gateway
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
